export interface Language {
    label: string
    value: string
}

export const GOOGLE_TRANSLATE_LANGUAGES: Language[] = [
    { label: "Afrikáans", value: "af" },
    { label: "Albanés", value: "sq" },
    { label: "Amhárico", value: "am" },
    { label: "Árabe", value: "ar" },
    { label: "Armenio", value: "hy" },
    { label: "Azerbaiyano", value: "az" },
    { label: "Vasco", value: "eu" },
    { label: "Bielorruso", value: "be" },
    { label: "Bengalí", value: "bn" },
    { label: "Bosnio", value: "bs" },
    { label: "Búlgaro", value: "bg" },
    { label: "Catalán", value: "ca" },
    { label: "Cebuano", value: "ceb" },
    { label: "Chino (Simplificado)", value: "zh-cn" },
    { label: "Chino (Tradicional)", value: "zh-tw" },
    { label: "Corso", value: "co" },
    { label: "Croata", value: "hr" },
    { label: "Checo", value: "cs" },
    { label: "Danés", value: "da" },
    { label: "Neerlandés", value: "nl" },
    { label: "Inglés", value: "en" },
    { label: "Esperanto", value: "eo" },
    { label: "Estonio", value: "et" },
    { label: "Finlandés", value: "fi" },
    { label: "Francés", value: "fr" },
    { label: "Frisón", value: "fy" },
    { label: "Gallego", value: "gl" },
    { label: "Georgiano", value: "ka" },
    { label: "Alemán", value: "de" },
    { label: "Griego", value: "el" },
    { label: "Guyaratí", value: "gu" },
    { label: "Criollo Haitiano", value: "ht" },
    { label: "Hausa", value: "ha" },
    { label: "Hawaiano", value: "haw" },
    { label: "Hebreo", value: "he" },
    { label: "Hindi", value: "hi" },
    { label: "Mong", value: "hmn" },
    { label: "Húngaro", value: "hu" },
    { label: "Islandés", value: "is" },
    { label: "Igbo", value: "ig" },
    { label: "Indonesio", value: "id" },
    { label: "Irlandés", value: "ga" },
    { label: "Italiano", value: "it" },
    { label: "Japonés", value: "ja" },
    { label: "Javanés", value: "jw" },
    { label: "Canarés", value: "kn" },
    { label: "Kazajo", value: "kk" },
    { label: "Khmer", value: "km" },
    { label: "Kinyarwanda", value: "rw" },
    { label: "Coreano", value: "ko" },
    { label: "Kurdo", value: "ku" },
    { label: "Kirguís", value: "ky" },
    { label: "Lao", value: "lo" },
    { label: "Latín", value: "la" },
    { label: "Letón", value: "lv" },
    { label: "Lituano", value: "lt" },
    { label: "Luxemburgués", value: "lb" },
    { label: "Macedonio", value: "mk" },
    { label: "Malgache", value: "mg" },
    { label: "Malayo", value: "ms" },
    { label: "Malayalam", value: "ml" },
    { label: "Maltés", value: "mt" },
    { label: "Maorí", value: "mi" },
    { label: "Maratí", value: "mr" },
    { label: "Mongol", value: "mn" },
    { label: "Birmano (Myanmar)", value: "my" },
    { label: "Nepalí", value: "ne" },
    { label: "Noruego", value: "no" },
    { label: "Chichewa (Nyanja)", value: "ny" },
    { label: "Odia (Oriya)", value: "or" },
    { label: "Pashto", value: "ps" },
    { label: "Persa", value: "fa" },
    { label: "Polaco", value: "pl" },
    { label: "Portugués", value: "pt" },
    { label: "Punjabi", value: "pa" },
    { label: "Rumano", value: "ro" },
    { label: "Ruso", value: "ru" },
    { label: "Samoano", value: "sm" },
    { label: "Gaélico Escocés", value: "gd" },
    { label: "Serbio", value: "sr" },
    { label: "Sesotho", value: "st" },
    { label: "Shona", value: "sn" },
    { label: "Sindhi", value: "sd" },
    { label: "Cingalés (Singalés)", value: "si" },
    { label: "Eslovaco", value: "sk" },
    { label: "Esloveno", value: "sl" },
    { label: "Somalí", value: "so" },
    { label: "Español", value: "es" },
    { label: "Sundanés", value: "su" },
    { label: "Suajili", value: "sw" },
    { label: "Sueco", value: "sv" },
    { label: "Tagalo (Filipino)", value: "tl" },
    { label: "Tayiko", value: "tg" },
    { label: "Tamil", value: "ta" },
    { label: "Tártaro", value: "tt" },
    { label: "Telugú", value: "te" },
    { label: "Tailandés", value: "th" },
    { label: "Turco", value: "tr" },
    { label: "Turcomano", value: "tk" },
    { label: "Ucraniano", value: "uk" },
    { label: "Urdu", value: "ur" },
    { label: "Uigur", value: "ug" },
    { label: "Uzbeko", value: "uz" },
    { label: "Vietnamita", value: "vi" },
    { label: "Galés", value: "cy" },
    { label: "Xhosa", value: "xh" },
    { label: "Yidis", value: "yi" },
    { label: "Yoruba", value: "yo" },
    { label: "Zulú", value: "zu" }
];